### ISSUE TITLE
Views should be organized by controller

### ISSUE THREAD

**Issue by TheUrbina20** [JosMigue/electronic_billing_system#2]
I think keep the views organized by the controller that they correspond its a better idea. So instead of `electronicBilling`, you can rename the file to `new` and move it into a folder `billing`, then you can render it with `return view('billing.new');`

https://github.com/JosMigue/electronic_billing_system/blob/3d5b4589aac6ed22f451bb1ea6030d073b306c29/app/Http/Controllers/BillingController.php#L10

**Comment by JosMigue** [comment]
This issue is solved, I just forget to link it. :(
